title: "Tony"
description: "A CLI-themed site because that is what I do"
baseurl: ""
url: "https://tony.halcyonlane.com"

markdown: kramdown
sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - mise.toml
  - AGENTS.md
  - README.md
  - vite.config.js
  - package.json
  - package-lock.json
